repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3.9

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.41.0
    hooks:
    -   id: eslint
        files: \.(js|ts|tsx)$
        types: [file]
        additional_dependencies:
        -   eslint@8.41.0
        -   eslint-config-prettier@8.8.0
        -   typescript@5.0.4
        -   '@typescript-eslint/eslint-plugin@5.59.8'
        -   '@typescript-eslint/parser@5.59.8'

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.8.8
    hooks:
    -   id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, markdown]
