version: '3.8'

services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app
      - ./tests:/tests
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MAPBOX_TOKEN=${MAPBOX_TOKEN}
      - GOOGLE_KEY=${GOOGLE_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=True
    depends_on:
      - db
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  db:
    image: postgis/postgis:14-3.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bitemap

  # Will add frontend later when we get to milestone 5
  
volumes:
  postgres_data:
