FROM python:3.9-slim

WORKDIR /project

# Install system dependencies for psycopg2 and other libraries
RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy application code
COPY ./app /project/app
# Only copy the root tests directory
COPY ./tests /project/tests
COPY ./worker.py /project/worker.py
COPY ./ingest_test.py /project/ingest_test.py
COPY ./test-requirements.txt /project/test-requirements.txt

# Install app dependencies and test dependencies
RUN pip install -r /project/app/requirements.txt
RUN pip install -r /project/test-requirements.txt

# Set PYTHONPATH to ensure imports work correctly
ENV PYTHONPATH=/project

CMD ["pytest", "-xvs", "tests"]
