"""add place geom and indexes

Revision ID: 003_add_place_geom_and_indexes
Revises: 002_add_users
Create Date: 2025-05-24 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry


# revision identifiers, used by Alembic.
revision: str = '003_add_place_geom_and_indexes'
down_revision: Union[str, None] = '002_add_users' # Updated to correct revision ID
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.add_column('places', sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.create_index('ix_places_geom', 'places', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_places_name_trgm', 'places', [sa.text('lower(name)')], unique=False, postgresql_using='gin', postgresql_ops={'lower(name)': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_places_name_trgm', table_name='places', postgresql_using='gin')
    op.drop_index('ix_places_geom', table_name='places', postgresql_using='gist')
    op.drop_column('places', 'geom')
    op.execute("DROP EXTENSION IF EXISTS pg_trgm;")
    # ### end Alembic commands ###
